# Generated by Django 5.2 on 2025-07-03 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام و نام خانوادگی')),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد ملی')),
                ('education', models.CharField(blank=True, choices=[('diploma', 'دیپلم'), ('associate', 'فوق دیپلم'), ('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('phd', 'دکترا'), ('other', 'سایر')], max_length=50, null=True, verbose_name='تحصیلات')),
                ('job', models.CharField(blank=True, choices=[('student', 'دانشجو'), ('employee', 'کارمند'), ('freelancer', 'فریلنسر'), ('unemployed', 'بیکار'), ('other', 'سایر')], max_length=50, null=True, verbose_name='شغل')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='شماره موبایل')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تلفن ثابت')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس کامل پستی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
