# Generated by Django 5.2 on 2025-07-04 17:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('national_id', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('education', models.CharField(blank=True, choices=[('diploma', 'دیپلم'), ('associate', 'فوق دیپلم'), ('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('phd', 'دکترا'), ('other', 'سایر')], max_length=100, null=True, verbose_name='تحصیلات')),
                ('job', models.CharField(blank=True, choices=[('student', 'دانشجو'), ('employee', 'کارمند'), ('self_employed', 'صاحب کسب و کار/آزاد'), ('unemployed', 'بیکار'), ('retired', 'بازنشسته'), ('other', 'سایر')], max_length=100, null=True, verbose_name='شغل')),
                ('province', models.CharField(blank=True, choices=[('', 'انتخاب کنید'), ('tehran', 'تهران'), ('isfahan', 'اصفهان'), ('fars', 'فارس'), ('khorasan_razavi', 'خراسان رضوی'), ('alborz', 'البرز')], max_length=100, null=True, verbose_name='استان')),
                ('city', models.CharField(blank=True, choices=[('', 'انتخاب کنید'), ('tehran_city', 'تهران'), ('karaj', 'کرج'), ('mashhad', 'مشهد'), ('isfahan_city', 'اصفهان'), ('shiraz', 'شیراز')], max_length=100, null=True, verbose_name='شهر')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره موبایل')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تلفن')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس کامل پستی')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='آدرس ایمیل')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='customuser_groups_set', related_query_name='customuser_group', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_permissions_set', related_query_name='customuser_permission', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
